version: '3'
services:
  trothcam:
    image: versatile0010/numberone:latest
    container_name: numberone
    restart: always
    ports:
      - 8080:8080
    logging:
      driver: awslogs
      options:
        awslogs-group: "numberone-dev"
        awslogs-region: "ap-northeast-2"
        awslogs-stream: "dev-spring"

  redis:
    hostname: redis
    image: redis:latest
    ports:
      - 6379:6379
    logging:
      driver: awslogs
      options:
        awslogs-group: "numberone-dev"
        awslogs-region: "ap-northeast-2"
        awslogs-stream: "dev-redis"