version: '3'
services:
  trothcam:
    image: versatile0010/numberone:latest
    container_name: numberone
    restart: always
    ports:
      - 8080:8080

  redis:
    hostname: redis
    image: redis:latest
    ports:
      - 6379:6379